name = "dh-pages"
type = "javascript"

[build]
pages_build_output_dir = "dist"
command = ""  # 静态网站可留空，框架项目写 npm run build

[functions]
directory = "functions"

[[kv_namespaces]]
binding = "WEBSITES_KV"
id = "7d55b8bd29af4ccb9259169cb2c87424"
