# Pages 专用配置
name = "dh"
type = "javascript"

# 构建设置
[build]
# 静态网站输出目录
pages_build_output_dir = "dist"
# 构建命令，纯静态可留空；框架项目填 npm run build
command = ""

# Functions 目录
[functions]
directory = "functions"

# KV 命名空间
[[kv_namespaces]]
binding = "WEBSITES_KV"
id = "7d55b8bd29af4ccb9259169cb2c87424"
