name = "dh-worker"
main = "yibazhan/js/worker.js"
compatibility_date = "2026-02-23"

[assets]
directory = "./dist" # 请确保路径是你的实际构建输出目录

keep_vars = true

[[kv_namespaces]]
binding = "WEBSITES_KV"
id = "7d55b8bd29af4ccb9259169cb2c87424"
